version: '3.3'

services:
  app:
    image: viticis/wizserver
    container_name: wiz
    volumes:
      - ./data:/wiz/storage
      - /etc/localtime:/etc/localtime
    expose:
      - 80:80
      - 9269:9269/udp
    restart: always

networks:
  default:
    external:
      name: dev
