version: '3.3'

services:
  guacd:
    image: dushixiang/guacd:1.3.0
    container_name: guacd
    volumes:
      - ./data:/usr/local/next-terminal/data
    restart: always

  next-terminal:
    image: dushixiang/next-terminal
    container_name: next-terminal
    environment:
      DB: mysql
      MYSQL_HOSTNAME: mariadb
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: next-terminal
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
    expose:
      - 8088
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data:/usr/local/next-terminal/data
    restart:
      always

networks:
  default:
    external:
      name: dev
