version: '3.1'

services:
  app:
    image: 'mariadb'
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./data:/var/lib/mysql

networks:
  default:
    external:
      name: dev
